name: expensive_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.4.0
  provider: ^6.1.2
  get_it: ^7.6.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio: ^5.2.1
  uuid: ^3.0.7
  firebase_core: ^3.10.0
  cloud_firestore: ^5.6.2
  http: ^1.3.0 
  shared_preferences: ^2.4.0
  fl_chart: ^0.70.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2  
  build_runner: ^2.4.6
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
