// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRvtIq26F7mK79GxDuSpsRR1ZF-XJ9pX4',
    appId: '1:1010306613046:web:4e597969767d8c9ba1fd97',
    messagingSenderId: '1010306613046',
    projectId: 'expense-tracker-e658a',
    authDomain: 'expense-tracker-e658a.firebaseapp.com',
    storageBucket: 'expense-tracker-e658a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAutV8I4f5oCaN08bQPqqRUsu7uwVkO_jc',
    appId: '1:1010306613046:android:6472d4250ee01bb1a1fd97',
    messagingSenderId: '1010306613046',
    projectId: 'expense-tracker-e658a',
    storageBucket: 'expense-tracker-e658a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNaI3d_XmRHiE_ZrTxyphNRaaELmkDzKw',
    appId: '1:1010306613046:ios:55e730cbcc48449ea1fd97',
    messagingSenderId: '1010306613046',
    projectId: 'expense-tracker-e658a',
    storageBucket: 'expense-tracker-e658a.firebasestorage.app',
    iosBundleId: 'com.example.expensiveTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNaI3d_XmRHiE_ZrTxyphNRaaELmkDzKw',
    appId: '1:1010306613046:ios:55e730cbcc48449ea1fd97',
    messagingSenderId: '1010306613046',
    projectId: 'expense-tracker-e658a',
    storageBucket: 'expense-tracker-e658a.firebasestorage.app',
    iosBundleId: 'com.example.expensiveTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRvtIq26F7mK79GxDuSpsRR1ZF-XJ9pX4',
    appId: '1:1010306613046:web:20cf1762e7437797a1fd97',
    messagingSenderId: '1010306613046',
    projectId: 'expense-tracker-e658a',
    authDomain: 'expense-tracker-e658a.firebaseapp.com',
    storageBucket: 'expense-tracker-e658a.firebasestorage.app',
  );

}